### ISSUE TITLE
Migrate relnotes.k8s.io to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [kubernetes-sigs/release-notes#430]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Prerequisite

~There is still an open discussion about which GA4 property to use. Currently the main thread is here: https://github.com/kubernetes/website/issues/37801#issuecomment-1319363201.~

After discussions with @a-mccarthy, we've agreed to move forward with `G-JPP6RFM2BP`.

### Tasks

- [x] Decide which GA4 property & measurement ID to use (see prerequisites above): `G-JPP6RFM2BP`
- ~Connect UA ID from GA4 ID~: won't connect back from GA4 ID to avoid sending non-relnotes events to the UA ID
- [x] Enable GA4 site tag via [Netlify snippet injection] (leaving the UA site tag in place), "Google Analytics 4 - only in production", just before `</body>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-JPP6RFM2BP"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-JPP6RFM2BP');
  </script>
  {% endif %}
  ```
- [x] Confirm that the GA4 site tag is receiving events - confirmed by https://tagassistant.google.com
- [x] Confirm that the UA site tag (`UA-98841695-4`) is still receiving events - confirmed by https://tagassistant.google.com

### Notes

- Corresponding issue for main site:
  https://github.com/kubernetes/website/issues/35299

### Pre-migration website analytics info

- UA ID: `UA-98841695-4` ([analytics console](https://analytics.google.com/analytics/web/?pli=1#/report-home/a98841695w204594590p197952062))
- Website is an Angular single-page app

### Followup

- #468

/cc @caniszczyk @nate-double-u @a-mccarthy

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Done!
